### ISSUE TITLE
error in ckeditor and elfinder file broswer

### ISSUE THREAD

**Issue by webineh** [nova-framework/novacms#1]
i changed role admin to Company Manager then show bellow error after open ckeditor and elfinder file broswer

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Class 'App\Modules\Files\Controllers\Admin\Redirect' not found"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in D:\xampp\htdocs\gitlab\novacms\app\Modules\Files\Controllers\Admin\Files.php:73

**Comment by dcblogdev** [comment]
I've added use Redirect; to the files controller, try that.
