### ISSUE TITLE
Error on composer install

### ISSUE THREAD

**Issue by mantis-wd** [nova-framework/novacms#5]
When installing by composer I get the following error

 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'Nova\Cron\CronServiceProvider' not found

Called: /var/ ....../vendor/nova-framework/system/src/Foundation/ProviderRepository.php

**Comment by dcblogdev** [comment]
Sorry I haven't been keeping this up to date with the changes from the main framework. It's out of sync I'll update this in a few hours time.

**Comment by dcblogdev** [comment]
This is now fixed.
