### ISSUE TITLE
New error on Composer install

### ISSUE THREAD

**Issue by mantis-wd** [nova-framework/novacms#6]
{"error":{"type":"ErrorException","message":"Undefined variable: driver","file":"\/var\/www\/web\/vendor\/nova-framework\/system\/src\/Mail\/MailServiceProvider.php","line":294}}>

This error aperars in my console

**Comment by dcblogdev** [comment]
Yes confirmed, I've got the same error. I'm looking into this now.

**Comment by dcblogdev** [comment]
Okay found the issue please replace app/Config/Mail.php with the updated one https://github.com/nova-framework/novacms/blob/master/app/Config/Mail.php

**Comment by mantis-wd** [comment]
Thanks
